EventBundle\Entity\Event:
    type: entity
    table: null
    repositoryClass: EventBundle\Repository\EventRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: string
            length: 255
    lifecycleCallbacks: {  }
