<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX0iq1mc\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX0iq1mc/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX0iq1mc.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX0iq1mc\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerX0iq1mc\appDevDebugProjectContainer([
    'container.build_hash' => 'X0iq1mc',
    'container.build_id' => '200b1cd0',
    'container.build_time' => 1595003056,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX0iq1mc');
