<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXpxbh52\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXpxbh52/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXpxbh52.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXpxbh52\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXpxbh52\appDevDebugProjectContainer([
    'container.build_hash' => 'Xpxbh52',
    'container.build_id' => '422dd54c',
    'container.build_time' => 1594071866,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXpxbh52');
