<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTllxjq6\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTllxjq6/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTllxjq6.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTllxjq6\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTllxjq6\appDevDebugProjectContainer([
    'container.build_hash' => 'Tllxjq6',
    'container.build_id' => '45d3d3db',
    'container.build_time' => 1595543399,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTllxjq6');
